---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-stats
spec:
  replicas: 2
  selector:
    matchLabels:
      service: repo-stats
  serviceName: repo-stats
  template:
    spec:
      containers:
        - name: api
          image: 
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/ready
              scheme: HTTP
              port: 7000
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/live
              scheme: HTTP
              port: 7000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 6699
          command: ["./repo-stats"]
          resources:
            requests:
              memory: "128M"
              cpu: "0.1"
            limits:
              memory: "256M"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: repo-stats
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6699
  selector:
    service: repo-stats
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-stats
  annotations:
spec:
  defaultBackend:
    service:
      name: repo-stats
      port:
        number: 80
